name: Release

on:
  workflow_dispatch: 
    inputs:
      release_name:
        description: 'Name of this release like 28 or 28-rc1'
        type: string
      pre_release:
        description: 'is this a pre-release. Yes for releases like vXY-rcZ'
        type: boolean
      tag: 
        description: 'git tag to use like v28'
        type: string
jobs:
  build:
    name: Build for multiple platforms
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            platform: linux-debian
          - goos: windows
            goarch: amd64
            platform: windows
          - goos: darwin
            goarch: amd64
            platform: macos
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          if [ "${{ matrix.goos }}" = "windows" ]; then
            echo "go build -o golang_release-${{ matrix.platform }}.exe main.go" >> golang_release-${{ matrix.platform }}
          else
            echo "go build -o golang_release-${{ matrix.platform }} main.go" >> golang_release-${{ matrix.platform }}
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: golang_release-${{ matrix.platform }}
          path: golang_release-${{ matrix.platform }}*

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Create Release
        id: create_release
        uses: comnoco/create-release-action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag }}
          release_name: Release ${{ inputs.release_name }}
          draft: true
          prerelease: ${{ inputs.pre_release }}

      - name: Upload release artifacts
        id: upload_release_artifacts
        run: gh release upload --clobber ${{ github.ref_name }} -R $GITHUB_REPOSITORY $(find artifacts -type f ! -name "*.sha*")
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
